#!/usr/bin/awk -f

{
        H = $1
        sub("\\.h", "", H)
        found = 0
        for (i=4; i<=NF; i++) {
                if ($i == (H ".c")) { found = 1; break; }
        }
        if (found == 0) printf("irrelevant: %s in %s\n", $2, $1)
}

NF == 3 {
        print("unused:", $0)
}

NF == 4 {
        H = $1
        C = $4
        sub("\\.h", "", H)
        sub("\\.c", "", C)
        if (H == C)
                print("private:", $0)
        else
                print("nonexistent:", $0)
}
