#!/bin/sh

HEADER=$1
awk '
# skip non-function defs
/^#/ { next; }
/^ / { next; }
/^$/ { next; }
/^\// { next; }
/^extern/ { next; }
/^enum/ { next; }

# print every function name
{
        sub("\\*", "");
        sub("\\(.*", "");
        print $2
}
' $HEADER.h |
xargs -n 1 -J _ misc/audit_use_using ${HEADER} _
