K _6d(K a,K b);
K _6m(K x);
K _5d(K x,K y);
void printAtDepth(V u,K a,I d,I x,I vdep,I b);
K _5m(K x);
K _4m(K x);
K read_tape(I i,I type);
K _4d(K x,K y);
K kap(K *a,V v);
K popen_charvec(C *cmd);
K _3d(K x,K y);
K _bd(K x);
I ksender(I sockfd,K y,I t);
K Ki(I x);
I wipe_tape(I i);
K _3m(K x);
K kerr(cS s);
K _2d(K a,K b);
K _2m(K a);
S spn(S s,I n);
K Kv();
K rrep(V v,V aft,I *b,I y);
extern V vd[];
extern V vm[];
I sva(V p);
I rep(K x,I y);
I wrep(K x,V v,I y);
K _1d(K x,K y);
K mod(K a,K b);
I bp(I t);
K _2m_r(V v,V aft,I *b);
S glueSS(S c,S d);
K _1m(K x);
S sp(S k);
K formKfCS(S s);
K formKiCS(S s);
S strdupn(S s,I k);
I charpos(S s,C c);
I stringHasChar(S s,C c);
K _n();
K _0d(K a,K b);
K cd(K a);
K newK(I t,I n);
I stat_sz(S u,I *n);
S CSK(K x);
K _0m(K a);
