/* This file was automatically generated.  Do not edit! */
K _6d(K a,K b);
K _6m(K x);
K _5d(K x,K y);
void printAtDepth(V u,K a,I d,I x,I vdep,I b);
K _5m(K x);
K _4m(K x);
K read_tape(I i,I type);
K _4d(K x,K y);
K kap(K *a,V v);
I getline_(S *s,I *n,FILE *f);
K popen_charvec(C *cmd);
K _3d(K x,K y);
K _bd(K x);
I ksender(I sockfd,K y,I t);
I sendall(I s,S b,I k);
K Ki(I x);
I wipe_tape(I i);
K _3m(K x);
K kerr(S s);
K _2d(K a,K b);
K _2m(K a);
K readVector(K x,I t);
S spn(S s,I n);
I rrep_4(S *z,S a,S t);
K Kv();
K rrep(V v,V aft,I *b,I y);
extern V vd[];
extern V vm[];
I sva(V p);
I rep(K x,I y);
I wrep(K x,V v,I y);
I disk(K x);
K _1d_char(K x,K y);
K _1d_read(K a,K b);
K _1d_write(K x,K y);
K _1d(K x,K y);
I PG();
I bp(I t);
K _2m_r(V v,V aft,I *b);
K _1m_r(I f,V fixed,V v,V aft,I *b);
K _1m(K x);
S sp(S k);
S strdupn(S s,I k);
I charpos(S s,C c);
I stringHasChar(S s,C c);
K _n();
I ok_0dw(K b);
K _0d_read(K a,K b);
K _0d_write(K a,K b);
K _0d(K a,K b);
K cd(K a);
K newK(I t,I n);
I stat_sz(S u,I *n);
I getdelim_(S *s,I *n,I d,FILE *f);
K _0m(K a);
