/* This file was automatically generated.  Do not edit! */
K X(S s);
K workspace(S s);
K backslash_t(S s);
extern I SEED;
void seedPRNG(I s);
I StoI(S s,I *n);
K backslash(S s,I n);
K Ki(I x);
K precision_(void);
extern I PP;
extern C PPON;
extern I PPMAX;
K precision(UI n);
K _i();
K wd(S s,I n);
K ex(K a);
K backslash_s(S s);
K kap(K *a,V v);
I wdss(K *a,FILE *f);
K kerr(cS s);
K show(K a);
I parsedepth(PDA p);
I complete(S a,I n,PDA *q,I *marks);
I appender(S *s,I *n,S t,I k);
I getline_(S *s,I *n,FILE *f);
I wds(K *a,FILE *f);
I lines(FILE *f);
K _n();
K load(S s);
K cd(K a);
FILE *loadf(S s);
K newK(I t,I n);
K filename(S s);
I filexist(S s);
I prompt(I n);
void boilerplate();
