/* This file was automatically generated.  Do not edit! */
void init_genrand64(unsigned long long seed);
extern I SEED;
K _dot_t();
K newE(S s,K k);
K newEntry(S s);
K Kd();
extern K KTREE;
I test();
extern S IFS[3];
extern S IFP[3];
extern S LS;
S sp(S k);
extern S __d;
K Kn();
extern K NIL;
K kap(K *a,V v);
K newK(I t,I n);
I randomBits();
void seedPRNG(I s);
N newN();
extern N SYMBOLS;
extern V addressSSR,addressWhat,addressAt,addressDot,addressColon;
extern C vc[];
I charpos(S s,C c);
extern V vd[];
extern V adverbs[];
extern V vt_[];
extern V vd_[];
extern V vm_[];
extern V vn_[];
void finally();
I kinit();
extern K KFIXED;
K load(S s);
I args(int n,S *v);
K read_tape(I i,I type);
I wipe_tape(I i);
extern S PORT;
I attend();
extern fd_set master;
void pdafree(PDA p);
K cd(K a);
K wd(S s,I n);
K ex(K a);
K kerr(cS s);
K show(K a);
I parsedepth(PDA p);
I complete(S a,I n,PDA *q,I *marks);
I appender(S *s,I *n,S t,I k);
#if defined(__MACH__) || defined(__OpenBSD__)
I getline(S *s,I *n,FILE *f);
#endif
I line(FILE *f,S *a,I *n,PDA *p);
I lines(FILE *f);
I prompt(I n);
extern I adverb_ct;
extern I vn_ct,vm_ct,vd_ct,vt_ct;
