/* This file was automatically generated.  Do not edit! */
K mergeGrade(K a,I r);
K mergeGrade(K a,I r);
void doMergeGrade(K a,I r,K x,K y,I s,I t);
void doMergeGrade(K a,I r,K x,K y,I s,I t);
void merger(K a,I r,K x,K y,I s,I t,I m);
void merger(K a,I r,K x,K y,I s,I t,I m);
I mergerComparer(K a,I r,I i,I j);
I mergerComparer(K a,I r,I i,I j);
K charGrade(K a,I r);
K charGrade(K a,I r);
K cd(K a);
K _i();
K newK(I t,I n);
K distributionGrade(K a,I r,I u,I v);
K distributionGrade(K a,I r,I u,I v);
I SC(S a,S b);
K at(K x,K y);
I KC(K a,K b);
I KC(K a,K b);
I FC(F a,F b);
