/* This file was automatically generated.  Do not edit! */
K _dot_t();
double genrand64_real2(void);
I KC(K a,K b);
I FC(F a,F b);
I CIX(K a,I i,K x);
K _m();
K _k();
K _a();
K _u();
K _w();
K _p();
K _s();
K _f();
K _i();
K _v();
extern S __d;
K _d();
K _h();
extern K NIL;
K _T();
extern I k_epoch_offset;
K _t();
S rangematch(S p,C t,S r);
K _ss(K a,K b);
K demote(K a);
K promote(K a);
K _sm(K a,K b);
K _setenv(K a,K b);
F radius(F u,F v);
void svdcmp(F **a,I m,I n,F *w,F **v,F *t);
K _lsq(K a,K b);
C bottom(PDA p);
void vitter_a(I *a,I n,I N,I j);
K take_reshape(K a,K b);
void vitter(I *a,I n,I N);
F RF();
K _draw(K a,K b);
I binr(K a,I b,I c,K x);
K _bin(K x,K y);
K Kf(F x);
K _size(K a);
I stat_sz(S u,I *n);
K _ltime(K a);
K _lt(K a);
I jdn_from_date(I year,I month,I day);
K _jd(K a);
K _ic(K a);
K kerr(cS s);
S sp(S k);
K Ks(S x);
K Ki(I x);
K _host(K a);
K _n();
S CSK(K x);
K _getenv(K a);
I date_from_jdn(I j);
K _dj(K a);
K rrep(V v,V aft,I *b,I y);
K _db(K x);
K _ci(K a);
K floor_ceil(K a,F(*g)(F));
K _ceiling(K a);
I wrep(K x,V v,I y);
K _bd(K x);
I rep(K x,I y);
I net(K x);
K _abs(K a);
extern V vt_[];
extern V vd_[];
extern V vm_[];
extern V vn_[];
extern S vt_s[];
extern S vd_s[];
extern S vm_s[];
extern S n_s;
Z K _exit(K a);
K at(K x,K y);
K math(F(*f)(F),K a);
K ci(K a);
F sqr(F x);
extern _MATH;
K dot(K a,K b);
K X(S s);
#if defined(DEBUG)
extern I kreci;
#endif
K vf_ex(V q,K g);
K newK(I t,I n);
K cd(K a);
extern K KFIXED;
K kap(K *a,V v);
K XDB(S t);
