/* This file was automatically generated.  Do not edit! */
K enumerate(K a);
K atom(K a);
K mod(K a,K b);
K rotate(K a,K b);
K rotate_mod(K a,K b);
K not_attribute(K a);
S notsp(S a);
K colon_dyadic(K a,K b);
K colon_monadic(K a);
K dot_tetradic(K a,K b,K c,K y);
K at_tetradic(K a,K b,K c,K y);
I atomI(K a);
K at_ref(K *p,K b,K c,K y);
K specialAmendDot(K c,K args);
I isColonDyadic(K x);
I updateIndex(K *p,I x,K r);
K dot(K a,K b);
K enlist(K x);
K at_verb(K a,K b);
K lookup(K a,S b);
K *lookupEVOrCreate(K *p,S k);
K lookupEntryOrCreate(K *p,S k);
K *denameRecurse(K *p,S t,I create);
K *denameD(K *d,S t);
K *denameS(S dir_string,S t);
K EV(K e);
K *EAP(K e);
K *EVP(K e);
K *EIA(K a,I i);
K DE(K d,S b);
S ES(K d);
K DI(K d,I i);
K glue(K a,K b);
S glueSS(S c,S d);
K at(K x,K y);
K itemAtIndex(K a,I i);
