K promote(K a);
I bk(V p);
K join(K a,K b);
K count(K a);
I countI(K a);
K reverse(K a);
K where(K x);
K drop_cut(K a,K b);
K cut(K a,K b);
K drop(K a,K b);
K rotate(K a,K b);
K _i();
K shape(K a);
void shapeCheck(K a,K p,I d);
K take_reshape(K a,K b);
K take(K a,K b);
K reshape(K a,K b);
K _n();
K Ki(I x);
K Kf(F x);
K Kc(C x);
extern S LS;
K Ks(S x);
K first(K a);
K itemAtIndex(K a,I i);
K flip(K a);
I VAT(I i);
K group(K x);
K cd(K a);
I matchI(K a,K b);
I FC(F a,F b);
K range(K a);
K ci(K a);
K newK(I t,I n);
K enlist(K x);
K grade_down(K a);
K grade_up(K a);
K mergeGrade(K a,I r);
K distributionGrade(K a,I r,I u,I v);
K charGrade(K a,I r);
K at(K x,K y);
