/* This file was automatically generated.  Do not edit! */
K join(K a,K b);
K count(K a);
I countI(K a);
K reverse(K a);
K where(K x);
K drop_cut(K a,K b);
K cut(K a,K b);
K drop(K a,K b);
K rotate(K a,K b);
K shape(K a);
I firstDepth(K x);
void shapeCheck(K a,K p,I d);
K take_reshape(K a,K b);
K take(K a,K b);
K reshape(K a,K b);
K reshaper(K a,K b,I d,I f,I *p);
K first(K a);
K itemAtIndex(K a,I i);
K flip(K a);
I VAT(I i);
K group(K x);
I matchI(K a,K b);
K range(K a);
K enlist(K x);
K grade_down(K a);
K grade_up(K a);
K at(K x,K y);
K grade_updown(K a,I r);
