K X(S s);
extern I SEED;
void seedPRNG(I s);
I StoI(S s,I *n);
K backslash(S s,I n,K*dict);
K Ki(I x);
extern I PP;
extern C PPON;
extern I PPMAX;
extern I fCmplt;
K precision(UI n);
K wd(S s,I n);
K ex(K a);
K show(K a);
I getline_(S *s,I *n,FILE *f);
I wds(K *a,FILE*f);
I wds_(K *a,FILE *f,I l);
I lines(FILE *f);
K _n();
K load(S s);
K cd(K a);
K newK(I t,I n);
K filename(S s);
I prompt(I n);
I oerr();
void boilerplate();
extern I tmr_ival;
K DI(K d,I i);
S ES(K d);
