K ci(K a);
K vf_ex(V q,K g);
S CSK(K x);
K X(S s);
I ksender(I sockfd,K y,I t);
K _db(K x);
K newK(I t,I n);
K read_tape(I i,I type);
extern fd_set master;
K cd(K a);
I wipe_tape(I i);
extern M0 CP[FD_SETSIZE];
void *get_in_addr(struct sockaddr *sa);
