K ci(K a);
K* denameS(S dir_string, S t, I create);
K vf_ex(V q,K g);
S CSK(K x);
K X(S s);
I ksender(I sockfd,K y,I t);
K _db(K x);
K newK(I t,I n);
extern fd_set master;
K cd(K a);
I wipe_tape(I i);
void *get_in_addr(struct sockaddr *sa);
extern pthread_mutex_t execute_mutex;
extern S HTTP_PORT;
K _n();
extern C errmsg[256];
K Ki(I);
I bswapI(I n);
void dm1(S msg,M1*m);

K read_tape(I i,I j,I type);
extern M0 CP[FD_SETSIZE+1];
