S spn(S s,I n);
N newN();
extern N SYMBOLS;
V alloc(size_t sz);
S sp(S k);
I SC(S a,S b);
I StoI(S s,I *n);
I strlenn(S s,I k);
S strdupn(S s,I k);
I gradeS();
K newK(I t,I n);
K mergeGrade(K a,I r);
