K of(K a,K b);
K dot_tetradic_2(K *g,K b,K c,K y);
extern S LS;
K newE(S s,K k);
extern V offsetSSR,offsetWhat,offsetAt,offsetDot,offsetColon;
extern I adverb_ct;
extern V adverbs[];
extern S fBreak;
extern I fCheck;
K kap(K *a,V v);
K itemAtIndex(K a,I i);
K ex1(V *w,K k,I *i,I n,I f);
K _n();
extern C errmsg[256];
I bk(V p);
K wd_(S s,I n,K *dict,K func);
K ex(K a);
K DI(K d,I i);
K kcloneI(K a,const char*f,int n);
#define kclone(a) kcloneI(a,__FILE__,__LINE__)
K Kv();
K dot_tetradic(K a,K b,K c,K y);
K at_tetradic(K a,K b,K c,K y);
K dot(K a,K b);
K what_triadic(K a,K b,K c);
K what(K x,K y);
K eachpair();
K at(K x,K y);
K demote(K a);
K promote(K a);
K eachleft();
K eachright();
K each();
K reverse(K a);
K collapse(K x);
K drop(K a,K b);
I atomI(K a);
K scan();
I matchI(K a,K b);
K vf_ex(V q,K g);
K cd(K a);
I bp(I t);
K newK(I t,I n);
K first(K a);
K Ki(I x);
K Kf(F x);
I VA(V p);
K ci(K a);
K enlist(K x);
K join(K a,K b);
K over();
I valence(V p);
I sva(V p);
I adverbClass(V p);
K kerr(cS s);
K last(K a);
I kdefClass(I n);
