K floor_verb(K a);
I FC(F a,F b);
F FF(F f);
K ci(K a);
K floor_ceil(K a,F(*g)(F));
K max_or(K a,K b);
K min_and(K a,K b);
K Kf(F x);
K reciprocal(K x);
K divide(K a,K b);
K Ki(I x);
K negate(K x);
K minus(K a,K b);
K cd(K a);
K mod(K a,K b);
K times(K a,K b);
K plus(K a,K b);
K newK(I t,I n);
K at(K x,K y);
K power(K a,K b);
