K promote(K a);
I bk(V p);
K join(K a,K b);
K count(K a);
I countI(K a);
K demote(K x);
K reverse(K a);
K where(K x);
K drop_cut(K a,K b);
K cut(K a,K b);
K drop(K a,K b);
K rotate(K a,K b);
K _i();
K shape(K a);
K take_reshape(K a,K b);
K take(K a,K b);
K reshape(K a,K b);
K _n();
K Ki(I x);
K Kf(F x);
K Kc(C x);
extern S LS;
K Ks(S x);
K first(K a);
K itemAtIndex(K a,I i);
K flip(K a);
I VAT(I i);
K group(K x);
K cd(K a);
I matchI(K a,K b);
I FC(F a,F b);
K range(K a);
K ci(K a);
K newK(I t,I n);
K enlist(K x);
K grade_down(K a);
K grade_up(K a);
K mergeGrade(K a,I r);
K distributionGrade(K a,I r,uI u,uI v);
K radixGrade(K a,I r,uI h);
K charGrade(K a,I r);
K at(K x,K y);
void trst();
void elapsed(S);
V alloc(size_t);
K symGrade(K a,I r);
I cl2(I v);
K last(K a);
K joinI(K*a,K b);
