I atomI(K a);
K what(K x,K y);
K at_verb(K a,K b);
I countI(K a);
K take(K a,K b);
K sample(K x,K y);
void vitter(I *a,I n,I N);
F RF();
K what_triadic(K a,K b,K c);
K kerr(cS s);
K vf_ex(V q,K g);
K ci(K a);
K cd(K a);
K newK(I t,I n);
K Kf(F x);
I matchI(K a,K b);
I FC(F a,F b);
K Ki(I x);
K at(K x,K y);
K find(K a,K b);
K hash_find(K a,K b);
